version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: fpco/stack-build:lts-13.24
    steps:
      - checkout

      - run:
          name: Install native dependencies
          command: |
            apt update
            apt install ffmpeg

      - run:
          name: Query resolver & ghc version
          command: |
            ./ci/resolver > resolver.version
            ./ci/ghc-version $(cat resolver.version) >  ghc.version

      - restore_cache:
          keys:
                - stack--{{ arch }}--{{ checksum "ghc.version" }}--{{ checksum "resolver.version" }}--{{ checksum "komposition.cabal" }}--{{ checksum "stack.yaml" }}
                - stack--{{ arch }}--{{ checksum "ghc.version" }}--{{ checksum "resolver.version" }}--{{ checksum "komposition.cabal" }}
                - stack--{{ arch }}--{{ checksum "ghc.version" }}--{{ checksum "resolver.version" }}--resolver
                - stack--{{ arch }}--{{ checksum "ghc.version" }}--ghc

      - run: stack setup

      - save_cache:
          key:    stack--{{ arch }}--{{ checksum "ghc.version" }}--ghc
          paths:  [~/.stack, ~/project/.stack-work]

      - run:
          command: stack build --no-terminal --test --bench --only-dependencies -j1

      - save_cache:
          key:    stack--{{ arch }}--{{ checksum "ghc.version" }}--{{ checksum "resolver.version" }}--resolver
          paths:  [~/.stack, ~/project/.stack-work]

      - save_cache:
          key:    stack--{{ arch }}--{{ checksum "ghc.version" }}--{{ checksum "resolver.version" }}--{{ checksum "komposition.cabal" }}
          paths:  [~/.stack, ~/project/.stack-work]

      - run:
          command: stack build --no-terminal --test --no-run-tests --bench --no-run-benchmarks

      - save_cache:
          key:    stack--{{ arch }}--{{ checksum "ghc.version" }}--{{ checksum "resolver.version" }}--{{ checksum "komposition.cabal" }}--{{ checksum "stack.yaml" }}
          paths:  [~/.stack, ~/project/.stack-work]

      - run:
          name: Running unit tests
          command: stack test

      - deploy:
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" == "owickstrom" ]; then
              if [[ "$CIRCLE_BRANCH" == "master" ]]; then
                release
              fi
            fi

workflows:
  version: 2
  build-test:
    jobs:
      - build
      # - haddock:
      #     requires:
      #       - build
